name: inr-apodizations
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - typer
  - loguru
  - rich
  - pyyaml
  - tqdm
  - ruff
  - cudatoolkit=11.8
  - cudnn=8.9
  - numpy=1.26
  - ipython
  - ipykernel
  - matplotlib
  - scipy
  - pymust
  - pip:
    - tensorflow==2.10
    - cupy-cuda11x
    - python-dotenv
    #- keras-tuner[bayesian]
    - optuna
    - -e . # Install the current package in editable mode. Make sure to run this command from the root of the project where pyproject.toml is located.